[general]
import = [
  # "./themes/themes/kanagawa_dragon.toml"
]

[colors]
draw_bold_text_with_bright_colors = false

[cursor]
style.shape = "Block"
unfocused_hollow = true

[font]
size = 12

[font.glyph_offset]
x = 0
y = 0

[font.normal]
# family = "Hack Nerd Font"
family = "Adwaita Mono"

[font.bold]
family = "Adwaita Mono"

[font.italic]
family = "Adwaita Mono"

[font.bold_italic]
family = "Adwaita Mono"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[window]
# decorations = "none"
dynamic_padding = true
opacity = 1.0
# startup_mode="Maximized"
# startup_mode="Fullscreen"

[window.padding]
x = 0
y = 0
