#-------------------------------------------------------------------------------
## common
export EDITOR='nvim'
export TERMINAL='alacritty'
export TERM='alacritty'
export PAGER='less -R'
#-------------------------------------------------------------------------------
## change home dotfiles
export PYLINTHOME="$XDG_CACHE_HOME"/pylint
export PASSWORD_STORE_DIR="$HOME/.local/configs/personal/password-store"
export LESSHISTFILE='$XDG_CACHE_HOME/lessht'
export CUDA_CACHE_PATH="$XDG_CACHE_HOME"/nv
export GNUPGHOME="$HOME/.local/configs/personal/gnupg"
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc
export CARGO_HOME="$HOME/.local/cargo"
export RUSTUP_HOME="$HOME/.local/rustup"
export WINEPREFIX="$HOME/Games/wine"
export ELINKS_CONFDIR="$XDG_CONFIG_HOME/elinks"
export SSB_HOME="$XDG_DATA_HOME"/zoom
export GOPATH="$XDG_DATA_HOME"/go
export GOMODCACHE="$XDG_CACHE_HOME"/go/mod
#-------------------------------------------------------------------------------
#NODE
export NODE_REPL_HISTORY="$XDG_DATA_HOME"/node_repl_history 
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc
#-------------------------------------------------------------------------------
##Docker
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker 
#export DOCKER_HOST=unix:///run/user/1000/docker.sock
#-------------------------------------------------------------------------------
